on: 
  push:
    branches:
      - release

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: Checkout Files
      uses: actions/checkout@v1
    - name: Export
      uses: firebelley/godot-export@dev
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2/beta5/mono/Godot_v3.2-beta5_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2/beta5/mono/Godot_v3.2-beta5_mono_export_templates.tpz
        godot_template_version: 3.2.beta5.mono
        relative_project_path: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
